name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: npm build  🔧
        run: |
          npm i
          npm run build
      - name: Publish package on npm
        run: |
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build demo page 🔧
        run: npm run build:demo
      - name: Deploy Github Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist-example

